apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  destination:
    namespace: vlog-app
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mustafadincerr/aop2.git
    targetRevision: HEAD
    path: user-service
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
