apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: vlog-app
spec:
  destination:
    namespace: vlog-app
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/username/single-repo.git
    targetRevision: HEAD
    path: parent-app
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
